steps:
     build_and_run:
          when:
               event: [push]
               branch: main
          image: docker:26
          volumes:
               - /var/run/docker.sock:/var/run/docker.sock
          commands:
               - echo "Building Docker image..."
               - docker build -t my-local-app:latest .
               - echo "Restarting container..."
               - docker rm -f my-local-app || true
               - docker run -d --name my-local-app -p 3000:3000 my-local-app:latest
