steps:
     test_docker:
          image: docker:26
          volumes:
               - /var/run/docker.sock:/var/run/docker.sock
          commands:
               - docker ps
               - echo "✅ Docker socket available"
