steps:
     - name: build_and_deploy_nokan
       image: docker:26-cli
       when:
            event: push
            branch: main
       volumes:
            - /var/run/docker.sock:/var/run/docker.sock
       environment:
            NEXT_PUBLIC_SUPABASE_URL:
                 from_secret: NEXT_PUBLIC_SUPABASE_URL
            NEXT_PUBLIC_SUPABASE_ANON_KEY:
                 from_secret: NEXT_PUBLIC_SUPABASE_ANON_KEY
            GOOGLE_CLIENT_ID:
                 from_secret: GOOGLE_CLIENT_ID
            GOOGLE_CLIENT_SECRET:
                 from_secret: GOOGLE_CLIENT_SECRET
            NEXTAUTH_URL:
                 from_secret: NEXTAUTH_URL
            NEXTAUTH_SECRET:
                 from_secret: NEXTAUTH_SECRET
       commands:
            - docker version
            - |
                 printf '%s\n' \
                   "NEXT_PUBLIC_SUPABASE_URL=$${NEXT_PUBLIC_SUPABASE_URL}" \
                   "NEXT_PUBLIC_SUPABASE_ANON_KEY=$${NEXT_PUBLIC_SUPABASE_ANON_KEY}" \
                   "GOOGLE_CLIENT_ID=$${GOOGLE_CLIENT_ID}" \
                   "GOOGLE_CLIENT_SECRET=$${GOOGLE_CLIENT_SECRET}" \
                   "NEXTAUTH_URL=$${NEXTAUTH_URL}" \
                   "NEXTAUTH_SECRET=$${NEXTAUTH_SECRET}" \
                   > .env
            - docker build -t nokan-taskboard:latest .
            - docker rm -f nokan-taskboard || true
            - |
                 docker run -d --name nokan-taskboard -p 6969:3000 \
                   -e NEXT_PUBLIC_SUPABASE_URL="$${NEXT_PUBLIC_SUPABASE_URL}" \
                   -e NEXT_PUBLIC_SUPABASE_ANON_KEY="$${NEXT_PUBLIC_SUPABASE_ANON_KEY}" \
                   -e GOOGLE_CLIENT_ID="$${GOOGLE_CLIENT_ID}" \
                   -e GOOGLE_CLIENT_SECRET="$${GOOGLE_CLIENT_SECRET}" \
                   -e NEXTAUTH_URL="$${NEXTAUTH_URL}" \
                   -e NEXTAUTH_SECRET="$${NEXTAUTH_SECRET}" \
                   nokan-taskboard:latest
            - rm -f .env
