steps:
  - name: build_and_deploy_nokan
    image: docker:26-cli
    when:
      event: push
      branch: main
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - source: NEXT_PUBLIC_SUPABASE_URL
        target: NEXT_PUBLIC_SUPABASE_URL
      - source: NEXT_PUBLIC_SUPABASE_ANON_KEY
        target: NEXT_PUBLIC_SUPABASE_ANON_KEY
      - source: GOOGLE_CLIENT_ID
        target: GOOGLE_CLIENT_ID
      - source: GOOGLE_CLIENT_SECRET
        target: GOOGLE_CLIENT_SECRET
      - source: NEXTAUTH_URL
        target: NEXTAUTH_URL
      - source: NEXTAUTH_SECRET
        target: NEXTAUTH_SECRET
    commands:
      - echo "🐳 Checking Docker daemon..."
      - docker version
      - echo "🔍 Checking injected envs (safe preview)..."
      - echo "NEXT_PUBLIC_SUPABASE_URL -> ${NEXT_PUBLIC_SUPABASE_URL}"
      - echo "NEXT_PUBLIC_SUPABASE_ANON_KEY prefix -> $(echo "${NEXT_PUBLIC_SUPABASE_ANON_KEY}" | cut -c1-6)"
      - echo "GOOGLE_CLIENT_ID prefix -> $(echo "${GOOGLE_CLIENT_ID}" | cut -c1-6)"
      - echo "NEXTAUTH_URL -> ${NEXTAUTH_URL}"
      - echo "📝 Rendering .env for build stage..."
      - cat <<EOF > .env
NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
NEXTAUTH_URL=${NEXTAUTH_URL}
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
EOF
      - echo "🚀 Building nokan-taskboard image..."
      - docker build -t nokan-taskboard:latest .
      - echo "🧹 Removing old container if exists..."
      - docker rm -f nokan-taskboard || true
      - echo "▶️ Running new nokan-taskboard container..."
      - docker run -d --name nokan-taskboard -p 3000:3000 \
        -e NEXT_PUBLIC_SUPABASE_URL="${NEXT_PUBLIC_SUPABASE_URL}" \
        -e NEXT_PUBLIC_SUPABASE_ANON_KEY="${NEXT_PUBLIC_SUPABASE_ANON_KEY}" \
        -e GOOGLE_CLIENT_ID="${GOOGLE_CLIENT_ID}" \
        -e GOOGLE_CLIENT_SECRET="${GOOGLE_CLIENT_SECRET}" \
        -e NEXTAUTH_URL="${NEXTAUTH_URL}" \
        -e NEXTAUTH_SECRET="${NEXTAUTH_SECRET}" \
        nokan-taskboard:latest
      - rm -f .env
      - echo "✅ Deploy completed successfully!"
