steps:
     build_image:
          when:
               event: [push]
               branch: main
          image: woodpeckerci/plugin-docker
          settings:
               dockerfile: Dockerfile
               context: .
               repo: local-app
               tags: latest
               dry_run: true

     run_app:
          when:
               event: [push]
               branch: main
          image: local-app:latest
          detach: true
          commands:
               - echo "App started successfully ✅"
