pipeline:
     build_image:
          image: docker:26
          volumes:
               - /var/run/docker.sock:/var/run/docker.sock
          commands:
               - docker build -t my-app:latest .
               - docker images
