steps:
     build:
          image: docker:26
          volumes:
               - /var/run/docker.sock:/var/run/docker.sock
          commands:
               - docker version
               - echo "✅ Docker socket works"
